# https://github.com/imbatony/electorn-chinese-chess

# 发布测试环境

on:
  push:
    # Sequence of patterns matched against refs/tags
    branches:
      - 'test'

  workflow_dispatch:

name: 发布测试环境

permissions:
  contents: write
  id-token: write

jobs:
  build:
    name: Build Release & Upload Assets
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: 输出 github.ref
        run: echo ${{ github.ref }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build project Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install
      - run: npm run build:win-test
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}

      - name: 上传到腾讯云 cos
        run: npm run upload-oss -- ${{ secrets.COS_SECRETID }} ${{ secrets.COS_SECRETKEY }} win test

      # - name: release
      #   uses: softprops/action-gh-release@v1
      #   if: startsWith(github.ref, 'refs/tags/')
      #   with:
      #     draft: false
      #     files: |
      #       dist/*.exe
      #       dist/*.zip
      #       dist/*.dmg
      #       dist/*.AppImage
      #       dist/*.snap
      #       dist/*.deb
      #       dist/*.rpm
      #       dist/*.tar.gz
      #       dist/*.yml
      #       dist/*.blockmap
